### ISSUE TITLE
Doppins replacing unrelated requirement resulting in duplicate requirement specification

### ISSUE THREAD

**Issue by sklirg** [doppins/doppins-docker#5]
Take a look at https://github.com/dotKom/onlineweb4/pull/1588/commits/06d204c7d9c101b8ff716511ebf2f86633587bca. 

For some reason, Doppins want to remove django-guardian and replace it with django-taggit, resulting in django-taggit being specified twice in the same file.

**Comment by ekmartin** [comment]
What an ugly bug, will look into it. Thanks!

**Comment by sklirg** [comment]
It happened again! https://github.com/dotKom/onlineweb4/pull/1586/commits/222db797e84423cb4e0708215816633f0a0ac73e 😖

**Comment by ekmartin** [comment]
This shouldn't happen anymore now, thank you for letting us know - and hopefully it didn't break anything for you!
