### ISSUE TITLE
Doppins disappeared from repository

### ISSUE THREAD

**Issue by sklirg** [doppins/doppins-docker#6]
Hey there.

Suddenly all of Doppins' PRs disappeared from our repository: [dotKom/onlineweb4](https://github.com/dotKom/onlineweb4/).

For example, [this commit](https://github.com/dotKom/onlineweb4/commit/5dd8e9cc964cd298d1fdc70735e4e864562d6f98) now references a [non-existing PR](https://github.com/dotKom/onlineweb4/pull/1574). 

Any idea what has happened here?

**Comment by ekmartin** [comment]
Yep, it seems like our poor bot has been hidden from public by GitHub - for being a bot 🤖.
We've reached out to them, so hopefully we'll get it resolved. In the meantime Doppins will continue to create pull requests, but the author will now be one of the authenticated project members instead.

**Comment by ekmartin** [comment]
Everything should be back to normal now 😄
